image:
  repository: 10.105.221.46:4000/factorio-status-ui
  tag: latest
  pullPolicy: Always

service:
  name: factorio-status-ui
  type: ClusterIP
  externalPort: 80
  internalPort: 80

persistance:
  modsPersistantVolumeClaimName:
  savesPersistantVolumeClaimName:

factorio:
  host:
  port: 34197
  rconHost:
  rconPort: 27015
  serverName: "Helm Factorio Server"

ingress:
  enabled: false
  hosts:
    - chart-example.local
  annotations:
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
  tls:
    - secretName: factorio-tls
      hosts:
        - chart-example.local

